### ISSUE TITLE
import problem in Quill.js rich editor

### ISSUE THREAD

**Issue by cckaron** [LetsGoGet/GoGet#30]
### Mentioned in #28 

- rich editor import 問題
  - 面試經驗版 http://localhost/forums/forum/28 的 rich editor功能正常，但如果用 http://localhost/interview- experience/ 就會失效, 出現 quill isn't defined.
    - 推測是 rich_editor.js 依賴於 quill.js，若在 front-end html 中直接 call quill.js 會失效。
  - 這次改動後的狀況
    - 變成 http://localhost/interview-experience 的 rich editor功能正常 ， http://localhost/forums/forum/28 異常 (待查明原因)
    - rich editor 的字數計算功能偵測失效

**Comment by JJJamieee** [comment]
已修復rich editor import問題，發現問題不是在quill，而是在生成javascript event handler的時候，動態設定event handler的時候，要把設定event handler的地方寫成一個function才不會變成共用參數

已恢復rich editor 的字數計算功能

**Comment by cckaron** [comment]
Great work! 
Create PR #35
