### ISSUE TITLE
新增工作經驗版

### ISSUE THREAD

**Issue by cckaron** [LetsGoGet/GoGet#31]
### 工作經驗版開發 - 注意事項
1. 依照 spec 來製作 work_experience_forum.php
    1. Component 沿用
    2. 顯示文章：Forum→getcontent()暫時沿用面試經驗版
        1. 下個版本設計共用 html element
    3. Validator 沿用面試經驗版
        1. 先不用加rich editor的驗證 (only 必填)
    1. Create new branch from new-forum branch
        1. Named as Feature-work_experience_board
2. 注意要測試alias url instead of forum id url

**Comment by JJJamieee** [comment]
薪資區間 - Special Dropdown: 根據第一個dorpdown的選擇產生第二個dropdown的選項，選項對應內容以json檔案儲存

- country_dropdown獨立一個function，因為他是只有台灣會有對應的值，其他都直接填空白，不是一般use case，如果之後變為完全對應即可使用special_dropdown

- 引入函數的部分之後應該會再包裝起來，目前是直接在forum裡面new了dropdown後引入
